import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "News Tech Pro Bem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div> {children}</div>
      </body>
    </html>
  );
}
